name = "my-awsome-site"
main = "src/worker.js"
compatibility_date = "2024-08-08"

# Static assets configuration using [assets]
[assets]
directory = "public"

# Build configuration
[build]
command = "npm run build"

# Environment variables for production
[env.production]
name = "my-awsome-site"
vars = { NODE_ENV = "production" }
routes = [
  "augustaro.com/*"
]

# Environment variables for staging
[env.staging]
name = "augustaro-com-dev"
vars = { NODE_ENV = "staging" }
routes = [
  "staging.augustaro.com/*"
]

# Environment variables for development
[env.development]
vars = { NODE_ENV = "development" }

